# Generated by Django 3.0.5 on 2020-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('rmsACC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Acc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('rmsACC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Acc3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('rmsACC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('video_fileName', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='systemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_threshold', models.FloatField()),
            ],
        ),
    ]
