# Generated by Django 3.0.5 on 2020-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acc2',
        ),
        migrations.DeleteModel(
            name='Acc3',
        ),
        migrations.AlterField(
            model_name='event',
            name='video_fileName',
            field=models.CharField(max_length=26),
        ),
    ]
