# Generated by Django 3.0.5 on 2020-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_auto_20200503_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('rmsACC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Acc3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.CharField(max_length=16)),
                ('rmsACC', models.FloatField()),
            ],
        ),
    ]
