# Generated by Django 3.0.5 on 2020-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0003_acc2_acc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc1',
            name='fileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acc2',
            name='fileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acc3',
            name='fileUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='fileUploaded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
