# Generated by Django 3.0.5 on 2020-05-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0005_remove_event_fileuploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_fileName',
        ),
    ]
