# Generated by Django 3.0.5 on 2020-05-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0007_systemstate_icam'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='Time_acc1_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='Time_acc2_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='Time_acc3_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='Time_tmp1_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='Time_tmp2_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='Time_tmp3_gcUploaded',
            field=models.DateTimeField(null=True),
        ),
    ]
