# Generated by Django 3.0.5 on 2020-05-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0008_auto_20200516_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_acc1_gcUploaded',
            new_name='Time_gcUploaded_acc1',
        ),
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_acc2_gcUploaded',
            new_name='Time_gcUploaded_acc2',
        ),
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_acc3_gcUploaded',
            new_name='Time_gcUploaded_acc3',
        ),
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_tmp1_gcUploaded',
            new_name='Time_gcUploaded_tmp1',
        ),
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_tmp2_gcUploaded',
            new_name='Time_gcUploaded_tmp2',
        ),
        migrations.RenameField(
            model_name='systemstate',
            old_name='Time_tmp3_gcUploaded',
            new_name='Time_gcUploaded_tmp3',
        ),
    ]
